info:
  component: Zipkin Server

spring:
  application:
    name: zipkin-server

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      expose: '*'
  security:
    enabled: false