info:
  component: Gateway Server

spring:
  application:
    name: gateway-server
  sleuth:
    sampler:
      percentage: 1.0
    web:
    skipPattern: (^cleanup.*|.+favicon.*)
server:
  port: 8704

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

