info:
  component: Greeting Service Client

spring:
  application:
    name: greeting-service-client
  sleuth:
      sampler:
        percentage: 1.0
      #web:
      #skipPattern: (^cleanup.*|.+favicon.*)

server:
  port: 8702

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/