info:
  component: Greeting Service

spring:
  application:
    name: greeting-service
  sleuth:
      sampler:
        percentage: 1.0
      #web:
      #skipPattern: (^cleanup.*|.+favicon.*)
server:
  port: 8701

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      expose: '*'
  security:
    enabled: false